language: rust
rust:
#  - stable
#  - beta
  - nightly
env:
  - GTK=3.18
addons:
  apt:
    packages:
      - libgtk-3-dev
  code_climate:
    repo_token: d88d5447f631e5887055f052bec1ad2dfdc8a9ecd3edf0cac11df0dece5aa8d8
#matrix:
#  allow_failures:
#    - rust: nightly
script:
  - BUNDLE="gtk-3.18.1-2"
  - FEATURES=gtk_3_18
  - WD="$PWD"
  - cd "$HOME"
  - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/$BUNDLE/deps.txz"
  - tar -xf deps.txz
  - cd "$WD"
  - export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
  - cargo build --features "$FEATURES"
  - cargo test --features "$FEATURES"

