language: rust
rust:
  - stable
  - beta
  - nightly
env:
  - GTK=3.18
addons:
  apt:
    packages:
      - libgtk-3-dev
cache:
  apt: true

matrix:
  allow_failures:
    - rust: nightly
script:
  - BUNDLE="gtk-3.18.1-2"
  - FEATURES=gtk_3_18
  - WD="$PWD"
  - cd "$HOME"
  - curl -LO "https://github.com/gkoz/gtk-bootstrap/releases/download/$BUNDLE/deps.txz"
  - tar -xf deps.txz
  - cd "$WD"
  - export PKG_CONFIG_PATH="$HOME/local/lib/pkgconfig"
  - ./configure.sh --prefix /usr/local
  - cargo test --features "$FEATURES"
  - cargo build --release --features "$FEATURES"
  - sudo ./install.sh
  - sudo ./uninstall.sh

notifications:
  email: true

